language: php

php:
    - 7.0
    - 7.1
    - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script: 
  - ./vendor/bin/phpstan analyze --level=7 lib/
  - ./vendor/bin/phpstan analyze --level=7 tests/
  - ./vendor/bin/phpunit
