language: php

php:
    - 7.1
    - 7.2
    - 7.3
    
sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install

script:
    - vendor/bin/php-cs-fixer fix --dry-run
    - vendor/bin/phpstan analyse lib -c phpstan.neon
    - vendor/bin/phpunit
    - vendor/bin/phpbench run --report=aggregate --progress=travis --store --iterations=1
    - tests/Smoke/smoke_test.php --limit=100
    
